graph LR
  style Legend fill:#FFFFFF00,stroke:#000000;
  style Graph fill:#FFFFFF00,stroke:#000000;
  subgraph Legend
    direction LR
    xf1522833a4d242c5([""Up to date""]):::uptodate --- xeb2d7cac8a1ce544>""Function""]:::none
    xeb2d7cac8a1ce544>""Function""]:::none --- xd03d7c7dd2ddda2b([""Stem""]):::none
  end
  subgraph Graph
    direction LR
    x591dca96dcd9c07d>"case_study_madrid_preaggregate_od_data"]:::uptodate --> x6b1f8b80aab16747(["madrid_data_for_plots"]):::uptodate
    x0bc6f982ff2b7b68(["madrid_od_data_files"]):::uptodate --> x6b1f8b80aab16747(["madrid_data_for_plots"]):::uptodate
    x139674905a9bc0ab>"case_study_madrid_predownload_od_data"]:::uptodate --> x0bc6f982ff2b7b68(["madrid_od_data_files"]):::uptodate
    x5191724c02f0f524(["valencia_od_and_zones"]):::uptodate --> xdb693f8581b6dc3c(["valencia_data_for_plots"]):::uptodate
    x0b6d89a9b9620c3d(["valencia_osm"]):::uptodate --> xdb693f8581b6dc3c(["valencia_data_for_plots"]):::uptodate
    x5161457634929192>"case_study_valencia_biking_potential_prep"]:::uptodate --> xdb693f8581b6dc3c(["valencia_data_for_plots"]):::uptodate
    x5f83bd7cebe7328e(["valencia_od_data_files"]):::uptodate --> x5191724c02f0f524(["valencia_od_and_zones"]):::uptodate
    x91c5caad44425789>"case_study_valencia_preaggregate_od_data"]:::uptodate --> x5191724c02f0f524(["valencia_od_and_zones"]):::uptodate
    x3763d8b5f65bb699>"case_study_valencia_predownload_od_data"]:::uptodate --> x5f83bd7cebe7328e(["valencia_od_data_files"]):::uptodate
    xf2f69f7e7d47dde7>"get_cached_osm_data_from_zenodo"]:::uptodate --> x0b6d89a9b9620c3d(["valencia_osm"]):::uptodate
  end
  classDef uptodate stroke:#000000,color:#ffffff,fill:#354823;
  classDef none stroke:#000000,color:#000000,fill:#94a4ac;
  linkStyle 0 stroke-width:0px;
  linkStyle 1 stroke-width:0px;
